# Generated by Django 5.1.2 on 2024-10-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('prorector', 'Проректор'), ('reviewer', 'Проверяющий'), ('student', 'Студент')], default='student', max_length=10),
        ),
    ]
