# Generated by Django 5.1.2 on 2024-10-18 23:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('under_review', 'Проверяется'), ('in_progress', 'В процессе'), ('completed', 'Готово')], default='created', max_length=20)),
                ('sent_document', models.FileField(blank=True, null=True, upload_to='applications/send_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])])),
                ('ready_document', models.FileField(blank=True, null=True, upload_to='applications/ready_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('student_signature', models.FileField(blank=True, null=True, upload_to='applications/signatures/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prorector_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prorector_comments', to='applications.applicationcomment')),
                ('reviewer_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_comments', to='applications.applicationcomment')),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.applicationtype')),
            ],
        ),
    ]
