# Generated by Django 5.1.2 on 2024-10-19 01:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='fields_data',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApplicationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Текстовое поле'), ('image', 'Изображение'), ('document', 'Документ'), ('signature', 'Подпись')], max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.FileField(blank=True, null=True, upload_to='applications/templates/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])])),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='applications.applicationtype')),
            ],
        ),
    ]
