# Generated by Django 5.1.2 on 2024-10-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_fields_data_applicationfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfield',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
    ]
