# Generated by Django 5.1.2 on 2024-10-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicationfield_example'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationfield',
            name='application_type',
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='fields',
            field=models.ManyToManyField(related_name='application_types', to='applications.applicationfield'),
        ),
    ]
