# Generated by Django 5.1.2 on 2024-10-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='data',
        ),
        migrations.AlterField(
            model_name='application',
            name='fields_data',
            field=models.JSONField(default=dict),
        ),
    ]
