# Generated by Django 5.1.2 on 2024-10-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('under_review', 'Проверяется'), ('in_progress', 'В процессе'), ('completed', 'Готово'), ('rejected', 'Отклонено')], default='created', max_length=20),
        ),
    ]
