# Generated by Django 5.1.2 on 2024-10-20 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='example_document',
            field=models.FileField(blank=True, null=True, upload_to='applications/example_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'doc'])]),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('under_review', 'Проверяется'), ('in_progress', 'Отправлен на подписание'), ('completed', 'Готово'), ('rejected', 'Отклонено')], default='under_review', max_length=20),
        ),
    ]
